### PR TITLE
Naive update for newer version of ES

### LINKED ISSUE #29: Support for ES v7
Version 7 is already supported by `ruflin/elastica: ~7.0`. Notable changes:
 - strong typing for the `request` method in `client`

### PR DESCRIPTION
**Pull request by patrickkusebauch**
Closes #29 

BC Break: yes

I tested it on my own project and it is working fine. Specifically:
 - The DI is working
 - The Tracy Panel is working

Not tested:
 - extensive configuration
 - `on*` methods.

### CODE REVIEW

**Comment by dakorpar** [comment]
@patrickkusebauch Thanks!
I'm currently not into releasing new version because tagging this as 3.2.0 could crash some existing installation.
Monolog Elastica handler still does not support v7.0, so I'll wait for that and also I'll support php 8.0 in upcomming v4.0 version,
branch alias is added, so you can require v4.0.0 in your own composer file and use this version if needed just make sure to have

```
  "minimum-stability": "dev",
  "prefer-stable": true,
```

I'll try not to break things up in master :)

**Comment by patrickkusebauch** [comment]
@dakorpar I see, so this is really depending on https://github.com/Seldaek/monolog/issues/1399 being resolved and maybe even just https://github.com/Seldaek/monolog/pull/1476 being accepted? If so, I ming look into resolving these.

**Comment by dakorpar** [comment]
@patrickkusebauch yup sounds right, if monolog will support it I'll release v4.0.0, I'll just check there for php 8.0 support, but from what I see it should work as it is now.

**Comment by patrickkusebauch** [comment]
@dakorpar I prepared a [pull request for Monolog](https://github.com/Seldaek/monolog/pull/1523) that should allow you to release a new version.

**Comment by dakorpar** [comment]
@patrickkusebauch I prepared everything here, now I'd like to wait just new tag on rufflin/elastica so that they support php 8.

https://github.com/ruflin/Elastica/pull/1871
Shouldn't take long however, until then build for v8.0 is failing, so I can't merge it yet and do not want to tag new version without php 8.0 support since this will be 4.0.0, a new major tag... Hope it's not an issue for you...

**Pull request merged**
